### ISSUE TITLE
java.lang.IllegalStateException: Unable to register extension com.exxeta.iss.sonar.esql.core.EsqlSourceImporter

### ISSUE THREAD

**Issue by prtkgoswami** [EXXETA/sonar-esql-plugin#15]
Hi, I am using Sonar 5.6.3 & Sonar-scanner 3.0.3. When I am trying to analyze an ESQL Code, I get the following error:
INFO: Scanner configuration file: C:\Users\bradmin\Documents\SOFTWARES\G20 - IUA - SonarQube\5.6.3\sonar-scanner-3.0.3.778-windows\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Users\bradmin\.sonar\cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=133ms
INFO: User cache: C:\Users\bradmin\.sonar\cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=6ms
INFO: SonarQube server 5.6.3
INFO: Default locale: "en_IN", source code encoding: "windows-1252" (analysis is platform dependent)
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=23ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=49ms
INFO: Load active rules
INFO: Load active rules (done) | time=420ms
INFO: Publish mode
INFO: -------------  Scan ESQLProject
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2.747s
INFO: Final Memory: 43M/163M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to register extension com.exxeta.iss.sonar.esql.core.EsqlSourceImporter
        at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:248)
        at org.sonar.batch.bootstrap.ExtensionInstaller.doInstall(ExtensionInstaller.java:76)
        at org.sonar.batch.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
        at org.sonar.batch.scan.ModuleScanContainer.addExtensions(ModuleScanContainer.java:179)
        at org.sonar.batch.scan.ModuleScanContainer.doBeforeStart(ModuleScanContainer.java:95)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:140)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/resources/ProjectFileSystem
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.picocontainer.injectors.AdaptingInjection$1.run(AdaptingInjection.java:203)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.picocontainer.injectors.AdaptingInjection.injectionMethodAnnotated(AdaptingInjection.java:200)
        at org.picocontainer.injectors.AdaptingInjection.methodAnnotatedInjectionAdapter(AdaptingInjection.java:171)
        at org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:70)
        at org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
        at org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
        at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
        at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
        at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
        at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:246)
        ... 29 more
Caused by: java.lang.ClassNotFoundException: org.sonar.api.resources.ProjectFileSystem
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 43 more
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**Comment by ThomasPohl** [comment]
Hi, thanks for reporting this issue. 
Which version of the sonar plugin are you using? 
For sonar 5.6.3 you should be using the plugin version 2.0.0.

**Comment by ThomasPohl** [comment]
I just published a new release so, the latest plugin version is now 2.1.0
