### ISSUE TITLE
SonarQube 10 and ACE 12 Support

### ISSUE THREAD

**Issue by MichaelGutbrod** [EXXETA/sonar-esql-plugin#151]
Hey, the scan fails for SonarQube 10 and we will move to ACE V12..
Could you please add the support for this versions ?

SonarQube fails during start when the plugin is activated

java.lang.IllegalStateException: Fail to load plugin Esql[esql]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:81)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:660)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:214)
        at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:194)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:362)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:113)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:346)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/profiles/ProfileDefinition

**Comment by ThomasPohl** [comment]
ACE 12 Code should be scannable. If there is a new syntax that I missed, please open an issue for that.
SonarQube 10, will be the next step after solving the current issues
