### ISSUE TITLE
Something unknown for me results in hard Java error

### ISSUE THREAD

**Issue by t603** [EXXETA/sonar-esql-plugin#86]
Hi, Thomas,

running "esql-plugin-2.3.1.jar" inside "sonarqube-6.7.1\bin\windows-x86-64" and "sonar-scanner-cli-3.0.3.778-windows", I have found one more hard Java error. Sonar Scanner ends in hard Java error. Now I do not have any hint, what is wrong, so the code is little longer than usual. 

The code is: 

```
CREATE COMPUTE MODULE Test
  --simplified, obfuscated, etc.
	CREATE FUNCTION Main() RETURNS BOOLEAN
	BEGIN
    DECLARE ns000 NAMESPACE 'http://www.somewhere.com/v1';
		DECLARE ns002 NAMESPACE 'http://www.somewhere.com/v2';
		DECLARE ns001 NAMESPACE 'http://www.somewhere.com/v3';
		DECLARE inVar REFERENCE TO Environment;
		DECLARE outupdateOrderWhenParametersReq_v1Ref REFERENCE TO Environment;
		SET outupdateOrderWhenParametersReq_v1Ref.ns001:{'ele01'}.ns001:ele02 = FIELDVALUE(inVar.*:ele01.*:ele02);
		IF EXISTS(inVar) THEN
			SET outupdateOrderWhenParametersReq_v1Ref.ns001:{'ele01'}.ns001:ele02 = FIELDVALUE(inVar.*:ele01.*:ele02);
		END IF;
		IF EXISTS(inVar) THEN
			SET outupdateOrderWhenParametersReq_v1Ref.ns001:{'ele01'}.ns001:ele02 = FIELDVALUE(inVar.*:ele01.*:ele02);
		END IF;
		IF EXISTS(inVar) THEN
			SET outupdateOrderWhenParametersReq_v1Ref.ns001:{'ele01'}.ns001:ele02 = FIELDVALUE(inVar.*:ele01.*:ele02);
		END IF;
		RETURN TRUE;
	END;
END MODULE;

```
The error is: 

```
ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to analyse file: file:///C:/temp/temp/error08/Test.esql
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor.analyse(EsqlSquidSensor.java:166)
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor.analyseFiles(EsqlSquidSensor.java:132)
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor.execute(EsqlSquidSensor.java:308)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)

```
Regards, Stepan

**Comment by ThomasPohl** [comment]
OK, I found it. It's an issue with the NavigatingTreeCouldBeReferenceCheck.  Probably I need to refactor the whole class... For now it just doesn't throw the exception.
