### ISSUE TITLE
Unable to read user trace file

### ISSUE THREAD

**Issue by essiwkw** [EXXETA/sonar-esql-plugin#99]
The following exception was thrown. I am using IIB v10.0.06

16:58:23.914 ERROR: Error during SonarQube Scanner execution
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1967)
        at com.exxeta.iss.sonar.esql.codecoverage.TraceFileReader.readLine(Trace
FileReader.java:123)
        at com.exxeta.iss.sonar.esql.codecoverage.TraceFileReader.readTrace(Trac
eFileReader.java:68)
        at com.exxeta.iss.sonar.esql.codecoverage.AbstractAnalyzer.analyse(Abstr
actAnalyzer.java:63)
        at com.exxeta.iss.sonar.esql.codecoverage.TraceSensor.execute(TraceSenso
r.java:41)
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor$SonarQubeProductExecutor.ex
ecuteCoverageSensors(EsqlSquidSensor.java:375)
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor$SonarQubeProductExecutor.ex
ecuteCoverageSensors(EsqlSquidSensor.java:367)
        at com.exxeta.iss.sonar.esql.EsqlSquidSensor.execute(EsqlSquidSensor.jav
a:310)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)

        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecuto
r.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java
:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java
:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseE
xecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanCon
tainer.java:182)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer
.java:312)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectSc
anContainer.java:307)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanC
ontainer.java:281)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:122)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:
81)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContain
er.java:132)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.exec
ute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(Iso
latedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner
.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.j
ava:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by ThomasPohl** [comment]
Hi @essiwkw I have probably fixed your issue in the develop branch. Can you find the line causing the problem in the trace log? That way we can make sure the problem is really fixed.

**Comment by essiwkw** [comment]
@ThomasPohl , The line causing the issue is the second line as below:
```
2018-07-18 18:49:46.887572    10676   UserTrace   BIP2537I: Node 'com.xyz.dbaudit.XYZ_DB_AUDIT.InsertIntoDB': Executing statement   ''SET SQL_STATEMENT = 'INSERT INTO XYZ_IIB_DB.XYZ_DB.ESB_AUDIT_IN' || '(UNIQUE_REF_NUM,ORDERID,REQ_TSTAMP,RES_TSTAMP,MESSAGE_FLOW_NAME,BROKER_NAME,SOURCE,TARGET,STATUS,TRACKINGNUMBER,JOBID,TRANSACTIONNAME,EXECUTIONGROUP,MSG_ID,HOSTNAME,ERROR_DETAILS,X_TID)
                                       		Values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';'' at ('com.xyz.dbaudit.DB_AUDIT_InsertIntoDB.Main', '35.3'). 
```
